### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by sjaeckel** [okamototk/KanonProject#1]
Hi,

I've tried to build AngelFalls and KanonProject, but I wasn't successful for one of them. Building was done in the msys bash and windows command line with the same behavior.

My environment is

```
Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: c:\Programme\Apache Software Foundation\apache-maven-3.0.4
Java version: 1.6.0_32, vendor: Sun Microsystems Inc.
Java home: c:\Programme\Java\jdk1.6.0_32\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows xp", version: "5.1", arch: "x86", family: "windows"
```

When executing the install script the following warnings appear.

```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls-contrib:jar:0.9.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 69, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls-core:jar:0.9.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 61, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls-ui:jar:0.9.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 79, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls-reports:jar:0.9.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 45, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls-exchange:jar:0.9.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 84, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 92, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls-pkg:jar:0.9.0
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo.webstart:webstart-maven-plugin is missing. @ line 128, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.ultimania.kanon:angelfalls:pom:0.9
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 52, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

Building fails later for both, when calling "mvn assembly:assembly" with the following message:

```
...
[INFO] com/projity/pm/graphic/images/leaf.png already added, skipping
[INFO] ---------------------------------------------------
constituent[0]: file:/c:/Programme/Apache%20Software%20Foundation/apache-maven-3.0.4/lib/aether-api-1.13.1.jar
...
constituent[27]: file:/c:/Programme/Apache%20Software%20Foundation/apache-maven-3.0.4/lib/wagon-http-2.2-shaded.jar
constituent[28]: file:/c:/Programme/Apache%20Software%20Foundation/apache-maven-3.0.4/lib/wagon-provider-api-2.2.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
        at sun.nio.cs.SingleByteEncoder.encodeArrayLoop(SingleByteEncoder.java:91)
        at sun.nio.cs.SingleByteEncoder.encodeLoop(SingleByteEncoder.java:130)
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:544)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:252)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:106)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:190)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:111)
        at java.io.PrintStream.write(PrintStream.java:476)
        at java.io.PrintStream.print(PrintStream.java:619)
        at org.apache.maven.cli.PrintStreamLogger.info(PrintStreamLogger.java:110)
        at org.codehaus.plexus.logging.AbstractLogger.info(AbstractLogger.java:51)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:478)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:481)
[ repeating the last line lots of times ]
```

It'd be nice if you could have a look at that issue.
Can you tell me under which environment you were able to build the projects? Probably this could help to analyse the problem.

Thanks in advance,
Steffen

**Comment by okamototk** [comment]
try 

$ export MAVEN_OPTS="-Xmx500m -Xss128m"

**Comment by sjaeckel** [comment]
Thanks for your fast reply!

this leads to the following error

```
[ERROR] unable to create new native thread -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
```

**Comment by sjaeckel** [comment]
OK, I got it...setting _MAVEN_OPTS="-Xmx512m -Xms128m -Xss2m"_ fixed the problem
